name: update cron schedule


on:
  workflow_dispatch:
  push:
    branches: ['main']
    paths:
      - 'cron_schedule'

jobs:
  update_hosts:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: modify cron job entries
        run: 

